---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: odh-deployment
  namespace: odh
spec:
  components:
    dashboard:
      managementState: Managed
    workbenches:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    feastoperator:
      managementState: Managed      
    kueue:
      managementState: Removed
    codeflare:
      managementState: Removed
    ray:
      managementState: Removed
    modelmeshserving:
      managementState: Managed
    kserve:
      managementState: Managed
      serving:
        ingressGateway:
          certificate:
            type: SelfSigned
        managementState: Managed
        name: knative-serving
#  components:
#    codeflare:
#      managementState: Managed
#    dashboard:
#      managementState: Managed
#    ray:
#      managementState: Managed
#    workbenches:
#      managementState: Managed