---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpi-jobs-clr
rules:
  - apiGroups:
    - kubeflow.org
    resources:
    - mpijobs
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcad-mpi-crb
subjects:
- kind: ServiceAccount
  name: codeflare-operator-controller-manager
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: mpi-jobs-clr
  apiGroup: rbac.authorization.k8s.io